# Generated by Django 4.2.7 on 2026-02-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_category', models.CharField(choices=[('A', 'Category A - Motorcycle'), ('B', 'Category B - Car/Van'), ('C', 'Category C - Truck'), ('D', 'Category D - Bus')], max_length=5)),
                ('license_expiry', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ON_DUTY', 'On Duty'), ('OFF_DUTY', 'Off Duty'), ('ON_TRIP', 'On Trip'), ('SUSPENDED', 'Suspended')], default='OFF_DUTY', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
